<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWpf>true</UseWpf>
    <RootNamespace>SwInventreeAddin.Tests</RootNamespace>
    <AssemblyName>SwInventreeAddin.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Net.Http" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SwInventreeAddin\SwInventreeAddin.csproj">
      <Properties>OutputPath=bin_unit_test\net48\</Properties>
    </ProjectReference>
  </ItemGroup>
</Project>
